#Default Image
image: docker:latest

variables:
  DOCKER_TLS_CERTDIR: ''
  KUBE_DOMAIN: gitlab.bxsoft.com
  DOCKER_HOST: tcp://localhost:2375
  DEPLOYER_NAME: ${CI_REGISTRY_IMAGE}/kups

stages:
  - package
  - test
  - push
  - build_deployer
  - deploy
  
build:
  stage: package
  services:
    - docker:dind
  script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:tmp .
    - docker push $CI_REGISTRY_IMAGE:tmp
  only:
    - flux
test:
  stage: test
  services:
    - docker:dind
  script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - docker run -d --name hello $CI_REGISTRY_IMAGE:tmp
    - sleep 10s
    - TEST=$(docker run --link hello lucj/curl -s http://hello:8013)
    - $([ "${TEST:0:5}" = "Hello" ])
  only:
    - flux

push:
  stage: push
  services:
    - docker:dind
  script:
   - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
   - docker pull $CI_REGISTRY_IMAGE:tmp
   - docker tag $CI_REGISTRY_IMAGE:tmp $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
   - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
   - cat k8s/20-deploy.tpl | sed "s|__IMAGE_NAME__|$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA|" > k8s/20-deploy.yml
   - cat k8s/40-ingress.tpl | sed "s|__HOST_NAME__|$CI_PROJECT_NAME-$CI_ENVIRONMENT_NAME.$KUBE_DOMAIN|g" > k8s/40-ingress.yml
   
  only:
    - flux
