variables:
  DOCKER_TLS_CERTDIR: ''

stages:
  - package
  - test
  - push
  - deploy
  
build:
  image: docker:latest
  stage: package
  services:
    - docker:dind
  script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:tmp .
    - docker push $CI_REGISTRY_IMAGE:tmp
  only:
    - master
test:
  image: docker:latest
  stage: test
  services:
    - docker:dind
  script:
    - docker run -d --name hello $CI_REGISTRY_IMAGE:tmp
    - sleep 10s
    - TEST=$(docker run --link hello lucj/curl -s http://hello:8000)
    - $([ "${TEST:0:5}" = "Hello" ])
  only:
    - master

push:
  image: docker:latest
  stage: push
  services:
    - docker:dind
  script:
   - docker image pull $CI_REGISTRY_IMAGE:tmp
   - docker image tag $CI_REGISTRY_IMAGE:tmp $CI_REGISTRY_IMAGE:$CI_BUILD_REF
   - docker image tag $CI_REGISTRY_IMAGE:tmp $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
   - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
   - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF
   - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  only:
    - master

deploy:
  stage: deploy
  image: lucj/kubectl:1.15.2
  environment: test
  script:
    - kubectl config set-cluster karis --server=${K8S_SERVER} --certificate-authority="${CA_DATA}"
    - kubectl config set-credentials gitlab --token=${SERVICE_TOKEN}
    - kubectl config set-context default --cluster=karis --user=gitlab --namespace default
    - kubectl config use-context default
    - cat k8s/deploy.tpl | sed 's/GIT_COMMIT/'"$CI_BUILD_REF/" > k8s/deploy.yml
    - kubectl apply -f k8s
  only:
    - master
