#Default Image
image: docker:latest

variables:
  DOCKER_TLS_CERTDIR: ''
  KUBE_DOMAIN: gitlab.bxsoft.com
  DOCKER_HOST: tcp://localhost:2375

stages:
  - package
  - test
  - push
  - deploy
  
build:
  stage: package
  services:
    - docker:dind
  script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:tmp .
    - docker push $CI_REGISTRY_IMAGE:tmp
  only:
    - master
test:
  stage: test
  services:
    - docker:dind
  script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - docker run -d --name hello $CI_REGISTRY_IMAGE:tmp
    - sleep 10s
    - TEST=$(docker run --link hello lucj/curl -s http://hello:8013)
    - $([ "${TEST:0:5}" = "Hello" ])
  only:
    - master

push:
  stage: push
  services:
    - docker:dind
  script:
   - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
   - docker image pull $CI_REGISTRY_IMAGE:tmp
   - docker image tag $CI_REGISTRY_IMAGE:tmp $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
   - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  only:
    - master

deploy:
  stage: deploy
  image: lucj/kubectl:1.15.2
  environment:
    name: stage
    url: https://${CI_PROJECT_NAME}-${CI_ENVIRONMENT_NAME}.${KUBE_DOMAIN}/
  script:
    - kubectl config set-cluster k8s --server="${K8S_SERVER}"
    - kubectl config set clusters.k8s.certificate-authority-data ${CA_DATA}
    - kubectl config set-credentials gitlab --token="${SERVICE_TOKEN}"
    - kubectl config set-context default --cluster=karis --user=gitlab
    - kubectl config use-context default
    - cat k8s/20-deploy.tpl | sed "s|__IMAGE_NAME__|$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA|" > k8s/20-deploy.yml
    - cat k8s/40-ingress.tpl | sed "s|__HOST_NAME__|$CI_PROJECT_NAME-$CI_ENVIRONMENT_NAME.$KUBE_DOMAIN|g" > k8s/40-ingress.yml
    - kubectl delete ns mmartin
    - kubectl apply -f k8s/10-namespace.yml
    - kubectl apply -f k8s/20-deploy.yml
    - kubectl apply -f k8s/30-service.yml
    - kubectl apply -f k8s/40-ingress.yml
    - kubectl rollout status -f k8s/20-deploy.yml
  only:
    - master
