FROM alpine

ENV KURL="https://storage.googleapis.com/kubernetes-release/release"

RUN apk add --update ca-certificates \
 && apk add --update -t deps curl \
 && curl -L ${KURL}/$(curl -s ${KURL}/stable.txt)/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl \
 && chmod +x /usr/local/bin/kubectl \
 && apk del --purge deps \
 && rm /var/cache/apk/*

ENTRYPOINT ["kubectl"]
CMD ["help"]
